---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: shell

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: centos-6.7
  - name: centos-5.11

suites:
  - name: default
